---
before_install:
  - gem update --system
  - gem --version
  - gem update bundler
language: ruby
notifications:
  email:
    - mike@blowmage.com
rvm:
  - 2.1
  - 2.0
  - 1.9.3
env:
  - "RAILS_VERSION=4.1"
  - "RAILS_VERSION=4.2"
