---
before_install:
  - gem update --system
  - gem --version
  - gem update bundler

language: ruby

notifications:
  email:
    - mike@blowmage.com

rvm:
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - 2.0.0
  - 1.9.3

env:
  - "RAILS_VERSION=4.1"
  - "RAILS_VERSION=4.2"
